# Generated by Django 3.2.13 on 2022-05-25 12:36

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
